interface TelemetryData {
    speed: number;
    speedLimit: number;
    cruiseControl: boolean;
    cruiseControlSpeed: number;
    // Engine
    rpm: number;
    rpmMax: number;
    gear: number;
    gearDashboard: number;
    engineOn: boolean;
    engineEnabled: boolean;
    // Fuel
    fuel: number;
    fuelMax: number;
    fuelAvgConsumption: number;
    fuelRange: number;
    // Truck health
    truckWear: number;
    engineWear: number;
    transmissionWear: number;
    cabinWear: number;
    chassisWear: number;
    wheelsWear: number;
    // Trailer
    trailerAttached: boolean;
    trailerWear: number;
    trailerMass: number;
    trailerName: string;
    trailerCargoMass: number;
    // Job
    jobIncome: number;
    jobDeadline: number;
    jobRemainingTime: number;
    jobSourceCity: string;
    jobSourceCompany: string;
    jobDestinationCity: string;
    jobDestinationCompany: string;
    jobDistance: number;
    jobDistanceRemaining: number;
    jobCargoName: string;
    onJob: boolean;
    // Navigation
    navDistance: number;
    navTime: number;
    navSpeedLimit: number;
    // Lights
    blinkerLeft: boolean;
    blinkerRight: boolean;
    hazardBlinker: boolean;
    lightsParking: boolean;
    lightsBeamLow: boolean;
    lightsBeamHigh: boolean;
    lightsAux: boolean;
    lightsBeacon: boolean;
    lightsBrake: boolean;
    lightsReverse: boolean;
    // Warnings
    airPressureWarning: boolean;
    airPressureEmergency: boolean;
    fuelWarning: boolean;
    adblueWarning: boolean;
    oilPressureWarning: boolean;
    waterTemperatureWarning: boolean;
    batteryVoltageWarning: boolean;
    parkBrake: boolean;
    motorBrake: boolean;
    electricEnabled: boolean;
    // Pressure / temp
    airPressure: number;
    oilPressure: number;
    oilTemperature: number;
    waterTemperature: number;
    batteryVoltage: number;
    adblue: number;
    adblueMax: number;
    // Time
    gameTime: number;
    localTime: Date;
    gamePaused: boolean;
    gameName: string;
    webViewFocus: boolean;
    // Truck info
    truckMake: string;
    truckModel: string;
    truckLicensePlate: string;
    truckLicensePlateCountry: string;
    // Odometer
    odometer: number;
    // Acceleration
    accelerationX: number;
    accelerationY: number;
    accelerationZ: number;
    // Position
    coordinateX: number;
    coordinateY: number;
    coordinateZ: number;
    rotationX: number;
    rotationY: number;
    rotationZ: number;
    //
    money?: any;
    onAction?: boolean;
}
//
const defaultTelemetry: TelemetryData = {
    speed: 0,
    speedLimit: 90,
    cruiseControl: false,
    cruiseControlSpeed: 0,
    rpm: 0,
    rpmMax: 2500,
    gear: 0,
    gearDashboard: 0,
    engineOn: false,
    engineEnabled: false,
    fuel: 400,
    fuelMax: 600,
    fuelAvgConsumption: 35,
    fuelRange: 0,
    truckWear: 0,
    engineWear: 0,
    transmissionWear: 0,
    cabinWear: 0,
    chassisWear: 0,
    wheelsWear: 0,
    trailerAttached: false,
    trailerWear: 0,
    trailerMass: 0,
    trailerName: '',
    trailerCargoMass: 0,
    jobIncome: 0,
    jobDeadline: 0,
    jobRemainingTime: 0,
    jobSourceCity: '',
    jobSourceCompany: '',
    jobDestinationCity: '',
    jobDestinationCompany: '',
    jobDistance: 0,
    jobDistanceRemaining: 0,
    jobCargoName: '',
    onJob: false,
    navDistance: 0,
    navTime: 0,
    navSpeedLimit: 0,
    blinkerLeft: false,
    blinkerRight: false,
    hazardBlinker: false,
    lightsParking: false,
    lightsBeamLow: false,
    lightsBeamHigh: false,
    lightsAux: false,
    lightsBeacon: false,
    lightsBrake: false,
    lightsReverse: false,
    airPressureWarning: false,
    airPressureEmergency: false,
    fuelWarning: false,
    adblueWarning: false,
    oilPressureWarning: false,
    waterTemperatureWarning: false,
    batteryVoltageWarning: false,
    parkBrake: false,
    motorBrake: false,
    electricEnabled: false,
    airPressure: 8.5,
    oilPressure: 45,
    oilTemperature: 90,
    waterTemperature: 85,
    batteryVoltage: 27.5,
    adblue: 50,
    adblueMax: 60,
    gameTime: 480,
    localTime: new Date(),
    gamePaused: false,
    gameName: 'none',
    webViewFocus: false,
    truckMake: 'Volvo',
    truckModel: 'FH16',
    truckLicensePlate: 'PL 1234',
    truckLicensePlateCountry: 'pl',
    odometer: 125430,
    accelerationX: 0,
    accelerationY: 0,
    accelerationZ: 0,
    coordinateX: 0,
    coordinateY: 0,
    coordinateZ: 0,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    money: 0,
    onAction: false,
}
//
export type { TelemetryData };
export { defaultTelemetry };